-- [INDEX]
-- 1. FOOD_TYPE
-- 2.CATEGORY
-- 3. MEMBER
-- 4. CALENDAR

-- FOOD_TYPE INSERT
INSERT INTO FOOD_TYPE VALUES( 0,'백반');
INSERT INTO FOOD_TYPE VALUES( 1,'분식');
INSERT INTO FOOD_TYPE VALUES( 2,'커피');

-- 카테고리
-- 레벨 1
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'도서관 안내',NULL);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'자료 검색',NULL);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'참여마당',NULL);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'이용자 마당',NULL);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'맛있는 도서관',NULL);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'내 서재',NULL);

-- 레벨 2
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'도서관 소개',1);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'이용안내',1);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'시설안내',1);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'통합자료 검색',2);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'희망 도서 신청',2);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'교육문화 프로그램',3);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'열람실',3);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'세미나실',3);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'공지사항',4);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'문의사항',4);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'자주 묻는 질문',4);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'책 후기 나눠요',4);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'구내식당',5);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'카페',5);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'나의 도서관',6);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'결제내역',6);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'회원정보',6);

--레벨 3
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'인사말',7);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'연혁',7);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'조직도',7);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'도서관 오시는 길',7);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'주변 도서관',7);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'이용시간',8);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'도서관 달력',8);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'간략 검색',10);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'상세 검색',10);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'도서현황',21);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'예약 및 신청',21);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'즐겨찾기',21);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'내 정보',23);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'정보수정',23);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'내 글 관리',23);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'비밀번호 변경',23);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'회원탈퇴',23);

-- 레벨 4
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'대출중인 도서',33);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'이전 대출내역',33);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'예약내역',33);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'신청내역',33);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'좌석 예약현황',34);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'공간 예약현황',34);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'클래스 신청현황',34);

-- 재원씨 알아서 가져와야해요...
--INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'구내식당',23);
--INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'카페',23);

INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'게시글',38);
INSERT INTO CATEGORY VALUES( SEQ_CAT_CODE.NEXTVAL,'댓글',38);
-- 잘못만들었으면 create에 가서 다시 만들고 다시 insert
commit;

-- MEMBER
-- 비밀번호 'p'
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01@kh.or.kr', 
    '$2a$10$i6IHXqyhAXEz/FWz/eTjUuESsOZDtfha2SSNtI06PgQE16RlP6ucS',
    '유저일', '01011111111', 'F', '19991231', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02@kh.or.kr', 
    '$2a$10$i6IHXqyhAXEz/FWz/eTjUuESsOZDtfha2SSNtI06PgQE16RlP6ucS',
    '유저이', '01022222222', 'M', '19981130', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03@kh.or.kr', 
    '$2a$10$i6IHXqyhAXEz/FWz/eTjUuESsOZDtfha2SSNtI06PgQE16RlP6ucS',
    '유저삼', '01033333333', 'F', '19971029', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04@kh.or.kr', 
    '$2a$10$i6IHXqyhAXEz/FWz/eTjUuESsOZDtfha2SSNtI06PgQE16RlP6ucS',
    '유저사', '01044444444', 'M', '19960928', DEFAULT, DEFAULT, DEFAULT, DEFAULT);

-- 관리자 아이디
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', 
    '$2a$10$Hnbx25.rNytA8k974TK5fO/pgFxbceVUar18GrpOanU78QTmYjFn2',
    '관리자', '01012341234', 'M', '19950827', DEFAULT, DEFAULT, DEFAULT, 2);


COMMIT;

-- CALENDAR
-- 공휴일
-- 2024
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '신정', '2024-01-01', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '설 연휴', '2024-02-09', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '설', '2024-02-10', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '설 연휴', '2024-02-11', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '대체공휴일', '2024-02-12', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '삼일절', '2024-03-01', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '22대 국회의원 선거', '2024-04-10', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '근로자의 날(근로자만)', '2024-05-01', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '어린이날', '2024-05-05', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '부처님 오신 날', '2024-05-15', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '현충일', '2024-06-06', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '광복절', '2024-08-15', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '추석연휴', '2024-09-16', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '추석', '2024-09-17', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '추석연휴', '2024-09-18', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '개천절', '2024-10-03', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '한글날', '2024-10-09', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '크리스마스', '2024-12-25', NULL, 1);

-- 2025
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '신정', '2025-01-01', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '설 연휴', '2025-01-28', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '설', '2025-01-29', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '설 연휴', '2025-01-30', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '삼일절', '2025-03-01', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '대체공휴일', '2025-03-03', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '근로자의 날(근로자만)', '2025-05-01', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '어린이날', '2025-05-05', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '부처님 오신 날', '2025-05-05', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '대체공휴일', '2025-05-06', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '현충일', '2025-06-06', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '광복절', '2025-08-15', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '개천절', '2025-10-03', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '추석연휴', '2025-10-05', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '추석', '2025-10-06', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '추석연휴', '2025-10-07', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '대체공휴일', '2025-10-08', NULL, 1);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '한글날', '2025-10-09', NULL, 1);

INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '크리스마스', '2025-12-25', NULL, 1);

-- 휴관일(금요일)
-- 2024
-- 1월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-01-05', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-01-12', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-01-19', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-01-26', NULL, 2);

-- 2월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-02-02', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-02-09', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-02-16', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-02-23', NULL, 2);

-- 3월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-03-01', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-03-08', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-03-15', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-03-22', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-03-29', NULL, 2);

-- 4월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-04-05', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-04-12', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-04-19', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-04-26', NULL, 2);

-- 5월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-05-03', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-05-10', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-05-17', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-05-24', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-05-31', NULL, 2);

-- 6월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-06-07', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-06-14', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-06-21', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-06-28', NULL, 2);

-- 7월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-07-05', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-07-12', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-07-19', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-07-26', NULL, 2);

-- 8월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-08-02', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-08-09', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-08-16', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-08-23', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-08-30', NULL, 2);

-- 9월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-09-06', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-09-13', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-09-20', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-09-27', NULL, 2);

-- 10월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-10-04', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-10-11', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-10-18', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-10-25', NULL, 2);

-- 11월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-11-01', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-11-08', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-11-15', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-11-22', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-11-29', NULL, 2);

-- 12월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-12-06', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-12-13', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-12-20', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2024-12-27', NULL, 2);

-- 2025
-- 1월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-01-03', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-01-10', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-01-17', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-01-24', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-01-31', NULL, 2);

-- 2월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-02-07', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-02-14', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-02-21', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-02-28', NULL, 2);

-- 3월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-03-07', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-03-14', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-03-21', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-03-28', NULL, 2);

-- 4월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-04-04', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-04-11', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-04-18', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-04-25', NULL, 2);

-- 5월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-05-02', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-05-09', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-05-16', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-05-23', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-05-30', NULL, 2);

-- 6월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-06-06', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-06-13', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-06-20', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-06-27', NULL, 2);

-- 7월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-07-04', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-07-11', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-07-18', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-07-25', NULL, 2);

-- 8월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-08-01', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-08-08', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-08-15', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-08-22', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-08-29', NULL, 2);

-- 9월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-09-05', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-09-12', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-09-19', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-09-26', NULL, 2);

-- 10월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-10-03', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-10-10', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-10-17', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-10-24', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-10-31', NULL, 2);

-- 11월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-11-07', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-11-14', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-11-21', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-11-28', NULL, 2);

-- 12월
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-12-05', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-12-12', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-12-19', NULL, 2);
INSERT INTO CALENDAR VALUES( SEQ_CALENDAR_NO.NEXTVAL, '휴관일', '2025-12-26', NULL, 2);

COMMIT;


-- COFFEE
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 2, '아이스 아메리카노', 3500, DEFAULT, '/resources/images/food/iceAmericano.png', '아이스 아메리카노이다. 생명수이다.');
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 2, '아메리카노', 3500, DEFAULT, '/resources/images/food/hotAmericano.png', '뜨아거! 뜨거운 아메리카노이다. 뜨겁다.');
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 2, '자몽 허니 블렌디드', 3500, DEFAULT, '/resources/images/food/jamonghoneyblended.jpg', '자몽 허니 블렌디드이다. 경진언니의 픽이다.');
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 1, '라볶이', DEFAULT, DEFAULT, '/resources/images/food/rabokki.jpeg', null);
-- 백반 -- 
-- 첫번째 메뉴 --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오징어뭇국', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '된장국', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '삼계탕', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '콩나물국', DEFAULT, DEFAULT, NULL, NULL);
-- 금(휴관일) -- 
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '부대찌개', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오이냉국', DEFAULT, DEFAULT, NULL, NULL);

-- 두번째 메뉴 -- 
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '콩나물무침', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '멸치볶음', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '가지무침', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '흑미밥', DEFAULT, DEFAULT, NULL, NULL);
-- 금(휴관일) -- 
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '치킨', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오이김밥', DEFAULT, DEFAULT, NULL, NULL);

-- 세번째 메뉴 --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '계란말이', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오징어채무침', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '시금치나물', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '춘천닭갈비', DEFAULT, DEFAULT, NULL, NULL);
-- 금(휴관일) --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '가자미양념튀김', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오이소박이', DEFAULT, DEFAULT, NULL, NULL);

-- 네번째 메뉴 --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오이소박이', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '김', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '건새우마늘쫑볶음', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '진미채', DEFAULT, DEFAULT, NULL, NULL);
-- 금(휴관일) --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '김치', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오이무침', DEFAULT, DEFAULT, NULL, NULL);

-- 다섯번째 메뉴 --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '불고기', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '비엔나소시지볶음', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '깍두기', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '콩자반', DEFAULT, DEFAULT, NULL, NULL);
-- 금(휴관일) --
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '미역줄기볶음', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL, 0, '오이', DEFAULT, DEFAULT, NULL, NULL);
commit;

BEGIN
   FOR I IN 1..20 LOOP
      INSERT INTO BOARD 
      VALUES( SEQ_BOARD_NO.NEXTVAL,
                5, 15,
              I || '번째 공지사항',
              I || '번째 공지사항 내용 입니다.',
              DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
   END LOOP;
END;
/

BEGIN
   FOR I IN 1..100 LOOP
      INSERT INTO BOARD 
      VALUES( SEQ_BOARD_NO.NEXTVAL,
              CEIL(DBMS_RANDOM.VALUE(0,4)), 16,
              I || '번째 문의사항',
              I || '번째 문의사항 내용 입니다.',
              DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
   END LOOP;
END;
/
--DELETE FROM BOARD;
BEGIN
   FOR I IN 1..200 LOOP
      INSERT INTO BOARD 
      VALUES( SEQ_BOARD_NO.NEXTVAL,
             CEIL(DBMS_RANDOM.VALUE(0,4)), 18,
              I || '번째 후기글',
              I || '번째 후기글 내용 입니다.',
              DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
   END LOOP;
END;
/
commit;



