-- 주변 도서관 가져오기
SELECT BOARD_NO, BOARD_TITLE FROM BOARD
WHERE CAT_CODE = 28
ORDER BY BOARD_NO;

-- 주변 도서관 등록
-- 보드 숫자
SELECT SEQ_BOARD_NO.NEXTVAL FROM DUAL;

-- 일정 타입별로 구하기
SELECT CALENDAR_NO, CALENDAR_NAME, 
    TO_CHAR(START_DT,'YYYY-MM-DD') START_DT,
    TO_CHAR(END_DT + 1,'YYYY-MM-DD') END_DT,
    CALENDAR_TYPE
FROM CALENDAR
WHERE CALENDAR_TYPE = 2;

-- 일정 중 클래스로 구하기
SELECT S.BOARD_NO CALENDAR_NO,
        (SELECT BOARD_TITLE FROM BOARD C WHERE C.BOARD_NO = B.BOARD_NO) CALENDAR_NAME,
        TO_CHAR(START_DT,'YYYY-MM-DD') START_DT,
        TO_CHAR(END_DT + 1,'YYYY-MM-DD') END_DT
FROM CLASS_SCHEDULE S
JOIN BOARD B ON(B.BOARD_NO = S.BOARD_NO);

-- 클래스 더미 데이터
INSERT INTO BOARD 
VALUES( SEQ_BOARD_NO.NEXTVAL,
    1,12, '클래스 테스트', '클래스 일정 테스트', DEFAULT, NULL, DEFAULT, DEFAULT,DEFAULT);
COMMIT;
INSERT INTO CLASS_SCHEDULE
VALUES( SEQ_BOARD_NO.CURRVAL,'2024-09-25','2024-09-30','2024-09-14','2024-09-15',20);
COMMIT;

-- 일정중 특정 날짜 일정 가져오기
SELECT CALENDAR_NO, CALENDAR_NAME, 
    TO_CHAR(START_DT,'YYYY-MM-DD') START_DT,
    TO_CHAR(END_DT + 1,'YYYY-MM-DD') END_DT,
    CALENDAR_TYPE
FROM CALENDAR
WHERE CALENDAR_TYPE = 3
AND ( TO_CHAR( START_DT, 'YYYY-MM-DD') IN('2024-10-01') OR TO_CHAR((END_DT + 1), 'YYYY-MM-DD') IN('2024-10-01') 
OR '2024-10-01' BETWEEN TO_CHAR( START_DT, 'YYYY-MM-DD') AND TO_CHAR((END_DT + 1), 'YYYY-MM-DD') );

-- 행사 더미 데이터 
INSERT INTO CALENDAR VALUES(SEQ_CALENDAR_NO.NEXTVAL, '행사 테스트' ,SYSDATE, '2024-10-01',3);
COMMIT;

-- 클래스 일정중 특정 날짜 일정 가져오기
SELECT S.BOARD_NO CALENDAR_NO,
        (SELECT BOARD_TITLE FROM BOARD C WHERE C.BOARD_NO = B.BOARD_NO) CALENDAR_NAME,
        TO_CHAR(START_DT,'YYYY-MM-DD') START_DT,
        TO_CHAR(END_DT + 1,'YYYY-MM-DD') END_DT,
        TO_CHAR(RECRUITMENT_START_DT,'YYYY-MM-DD') RECRUITMENT_START_DT,
        TO_CHAR(RECRUITMENT_END_DT,'YYYY-MM-DD') RECRUITMENT_END_DT
        
FROM CLASS_SCHEDULE S
JOIN BOARD B ON(B.BOARD_NO = S.BOARD_NO)
WHERE ( TO_CHAR( START_DT, 'YYYY-MM-DD') IN('2024-10-01') OR TO_CHAR((END_DT + 1), 'YYYY-MM-DD') IN('2024-10-01') 
OR '2024-10-01' BETWEEN TO_CHAR( START_DT, 'YYYY-MM-DD') AND TO_CHAR((END_DT + 1), 'YYYY-MM-DD') );

-- 행사 , 휴관일 일정 가져오기
SELECT CALENDAR_NO, CALENDAR_NAME, 
    TO_CHAR(START_DT,'YYYY-MM-DD') START_DT,
    TO_CHAR(END_DT + 1,'YYYY-MM-DD') END_DT,
    CALENDAR_TYPE
FROM CALENDAR
WHERE CALENDAR_TYPE IN(2,3);
