SELECT * FROM
(SELECT LEVEL LEV, C.* FROM 
    (SELECT COMMENT_NO, COMMENT_CONTENT,
        TO_CHAR(C_CREATE_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') C_CREATE_DATE,
        BOARD_NO, MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG,PARENT_NO, COMMENT_DEL_FL
    FROM "COMMENT"
    JOIN MEMBER USING(MEMBER_NO)
    WHERE BOARD_NO = 1509
    ORDER BY COMMENT_NO) C
WHERE COMMENT_DEL_FL = 'N'
START WITH PARENT_NO IS NULL
CONNECT BY PRIOR COMMENT_NO = PARENT_NO
ORDER SIBLINGS BY COMMENT_NO)
WHERE LEV = 4;

SELECT LEVEL , C.* FROM
    (SELECT * FROM CATEGORY) C
START WITH PARENT_CODE IS NULL
CONNECT BY PRIOR CAT_CODE = PARENT_CODE
ORDER SIBLINGS BY PARENT_CODE;